service: mtgml-payment

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true
  exclude:
    - data/**
    - notebooks/**
  include:
    - ../../libs/**

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  tracing:
    lambda: true

  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId

  environment:
    USERS_TABLE: ${self:custom.usersTable}
    SUBSCRIPTIONS_TABLE: ${self:custom.subscriptionsTable}
    GLOBAL_DECKS_TABLE: ${self:custom.globalDecksTable}
    GLOBAL_CARDS_TABLE: ${self:custom.globalCardsTable}
    USER_DECKS_TABLE: ${self:custom.userDecksTable}
    USER_CARDS_TABLE: ${self:custom.userCardsTable}
    STRIPE_PUBLIC_KEY: ${self:custom.stripe_public_keys.${self:custom.stage}, self:custom.stripe_public_keys.dev}
    STRIPE_SECRET_KEY: ${self:custom.stripe_secret_keys.${self:custom.stage}, self:custom.stripe_secret_keys.dev}
    STRIPE_SIGNING_SECRET: ${env:STRIPE_SIGNING_SECRET}
    stage: ${self:custom.stage}
    resources_stage: ${self:custom.resources_stage}

  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'Fn::ImportValue': ${self:custom.resources_stage}-UsersTableArn
        - 'Fn::ImportValue': ${self:custom.resources_stage}-SubscriptionsTableArn
        - 'Fn::ImportValue': ${self:custom.resources_stage}-GlobalDecksTableArn
        - 'Fn::ImportValue': ${self:custom.resources_stage}-GlobalCardsTableArn
        - 'Fn::ImportValue': ${self:custom.resources_stage}-UserDecksTableArn
        - 'Fn::ImportValue': ${self:custom.resources_stage}-UserCardsTableArn

functions:
  subscribe:
    handler: subscribe.main
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: subscribe
          method: post
          cors: true
          authorizer: aws_iam
  checkout_complete:
    handler: checkout_complete.main
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: checkout_complete
          method: get
          cors: true
      - http:
          path: checkout_complete
          method: post
          cors: true
  payment:
    handler: payment.main
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: payment
          method: get
          cors: true
          authorizer: aws_iam
